
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: frontend-sa
      containers:
        - name: frontend
          image: fridade/fritz:dbfront_end
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: frontend-secret
                  key: DB_USER
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: frontend-secret
                  key: DB_PASS
            - name: MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: DB_NAME
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongodb

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
type: Opaque
data:
  DB_USER: "ZnJpdHo="
  DB_PASS: "ZGFtaWVu"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  DB_NAME: "mongo"
  #LOG_LEVEL: "info"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 8081
      nodePort: 30000


